image_array = [
  'image0.jpg',
  'image1.jpg',
  'image2.jpg',
  'image3.jpg',
  'image4.jpg',
  'image5.jpg',
  'image6.jpg',
  'image7.jpg',
  'image8.jpg',
  'image9.jpg',
  'image10.jpg',
  'image11.jpg',
  'image12.jpg',
  'image13.jpg',
  'image14.jpg',
  'image15.jpg',
  'image16.jpg',
  'image17.jpg',
  'image18.jpg',
  'image19.jpg',
  'image20.jpg',
  'image21.jpg',
  'image22.jpg',
  'image23.jpg',
  'image24.jpg',
  'image25.jpg',
  'image26.jpg',
  'image27.jpg',
  'image28.jpg',
  'image29.jpg',
  'image30.jpg',
  'image31.jpg',
  'image32.jpg',
  'image33.jpg',
  'image34.jpg',
  'image35.jpg',
  'image36.jpg',
  'image37.jpg',
  'image38.jpg',
  'image39.jpg',
  'image40.jpg',
  'image41.jpg',
  'image42.jpg',
  'image43.jpg',
  'image44.jpg',
  'image45.jpg',
  'image46.jpg',
  'image47.jpg',
  'image48.jpg',
  'image49.jpg',
  'image50.jpg',
  'image51.jpg',
  'image52.jpg',
  'image53.jpg',
  'image54.jpg',
  'image55.jpg',
  'image56.jpg',
  'image57.jpg',
  'image58.jpg',
  'image59.jpg',
  'image60.jpg',
  'image61.jpg',
  'image62.jpg',
  'image63.jpg',
  'image64.jpg',
  'image65.jpg',
  'image66.jpg',
  'image67.jpg',
  'image68.jpg',
  'image69.jpg',
  'image70.jpg',
  'image71.jpg',
  'image72.jpg',
  'image73.jpg',
  'image74.jpg',
  'image75.jpg',
  'image76.jpg',
  'image77.jpg',
  'image78.jpg',
  'image79.jpg',
  'image80.jpg',
  'image81.jpg',
  'image82.jpg',
  'image83.jpg',
  'image84.jpg',
  'image85.jpg',
  'image86.jpg',
  'image87.jpg',
  'image88.jpg',
  'image89.jpg',
  'image90.jpg',
  'image91.jpg',
  'image92.jpg',
  'image93.jpg',
  'image94.jpg',
  'image95.jpg',
  'image96.jpg',
  'image97.jpg',
  'image98.jpg',
  'image99.jpg',
  'image100.jpg',
  'image101.jpg',
  'image102.jpg',
  'image103.jpg',
  'image104.jpg',
  'image105.jpg',
  'image106.jpg',
  'image107.jpg',
  'image108.jpg',
  'image109.jpg',
  'image110.jpg',
  'image111.jpg',
  'image112.jpg',
  'image113.jpg',
  'image114.jpg',
  'image115.jpg',
  'image116.jpg',
  'image117.jpg',
  'image118.jpg',
  'image119.jpg',
  'image120.jpg',
  'image121.jpg',
  'image122.jpg',
  'image123.jpg',
  'image124.jpg',
  'image125.jpg',
  'image126.jpg',
  'image127.jpg',
  'image128.jpg',
  'image129.jpg',
  'image130.jpg',
  'image131.jpg',
  'image132.jpg',
  'image133.jpg',
  'image134.jpg',
  'image135.jpg',
  'image136.jpg',
  'image137.jpg',
  'image138.jpg',
  'image139.jpg',
  'image140.jpg',
  'image141.jpg',
  'image142.jpg',
  'image143.jpg',
  'image144.jpg',
  'image145.jpg',
  'image146.jpg',
  'image147.jpg',
  'image148.jpg',
  'image149.jpg',
  'image150.jpg',
  'image151.jpg',
  'image152.jpg',
  'image153.jpg',
  'image154.jpg',
  'image155.jpg',
  'image156.jpg',
  'image157.jpg',
  'image158.jpg',
  'image159.jpg',
  'image160.jpg',
  'image161.jpg',
  'image162.jpg',
  'image163.jpg',
  'image164.jpg',
  'image165.jpg',
  'image166.jpg',
  'image167.jpg',
  'image168.jpg',
  'image169.jpg',
  'image170.jpg',
  'image171.jpg',
  'image172.jpg',
  'image173.jpg',
  'image174.jpg',
  'image175.jpg',
  'image176.jpg',
  'image177.jpg',
  'image178.jpg',
  'image179.jpg',
  'image180.jpg',
  'image181.jpg',
  'image182.jpg',
  'image183.jpg',
  'image184.jpg',
  'image185.jpg',
  'image186.jpg',
  'image187.jpg',
  'image188.jpg',
  'image189.jpg',
  'image190.jpg',
  'image191.jpg',
  'image192.jpg',
  'image193.jpg',
  'image194.jpg',
  'image195.jpg',
  'image196.jpg',
  'image197.jpg',
  'image198.jpg',
  'image199.jpg',
  'image200.jpg',
  'image201.jpg',
  'image202.jpg',
  'image203.jpg',
  'image204.jpg',
  'image205.jpg',
  'image206.jpg',
  'image207.jpg',
  'image208.jpg',
  'image209.jpg',
  'image210.jpg',
  'image211.jpg',
  'image212.jpg',
  'image213.jpg',
  'image214.jpg',
  'image215.jpg',
  'image216.jpg',
  'image217.jpg',
  'image218.jpg',
  'image219.jpg',
  'image220.jpg',
  'image221.jpg',
  'image222.jpg',
  'image223.jpg',
  'image224.jpg',
  'image225.jpg',
  'image226.jpg',
  'image227.jpg',
  'image228.jpg',
  'image229.jpg',
  'image230.jpg',
  'image231.jpg',
  'image232.jpg',
  'image233.jpg',
  'image234.jpg',
  'image235.jpg',
  'image236.jpg',
  'image237.jpg',
  'image238.jpg',
  'image239.jpg',
  'image240.jpg',
  'image241.jpg',
  'image242.jpg',
  'image243.jpg',
  'image244.jpg',
  'image245.jpg',
  'image246.jpg',
  'image247.jpg',
  'image248.jpg',
  'image249.jpg',
  'image250.jpg',
  'image251.jpg',
  'image252.jpg',
  'image253.jpg',
  'image254.jpg',
  'image255.jpg',
  'image256.jpg',
  'image257.jpg',
  'image258.jpg',
  'image259.jpg',
  'image260.jpg',
  'image261.jpg',
  'image262.jpg',
  'image263.jpg',
  'image264.jpg',
  'image265.jpg',
  'image266.jpg',
  'image267.jpg',
  'image268.jpg',
  'image269.jpg',
  'image270.jpg',
  'image271.jpg',
  'image272.jpg',
  'image273.jpg',
  'image274.jpg',
  'image275.jpg',
  'image276.jpg',
  'image277.jpg',
  'image278.jpg',
  'image279.jpg',
  'image280.jpg',
  'image281.jpg',
  'image282.jpg',
  'image283.jpg',
  'image284.jpg',
  'image285.jpg',
  'image286.jpg',
  'image287.jpg',
  'image288.jpg',
  'image289.jpg',
  'image290.jpg',
  'image291.jpg',
  'image292.jpg',
  'image293.jpg',
  'image294.jpg',
  'image295.jpg',
  'image296.jpg',
  'image297.jpg',
  'image298.jpg',
  'image299.jpg',
  'image300.jpg',
  'image301.jpg',
  'image302.jpg',
  'image303.jpg',
  'image304.jpg',
  'image305.jpg',
  'image306.jpg',
  'image307.jpg',
  'image308.jpg',
  'image309.jpg',
  'image310.jpg',
  'image311.jpg',
  'image312.jpg',
  'image313.jpg',
  'image314.jpg',
  'image315.jpg',
  'image316.jpg',
  'image317.jpg',
  'image318.jpg',
  'image319.jpg',
  'image320.jpg',
  'image321.jpg',
  'image322.jpg',
  'image323.jpg',
  'image324.jpg',
]


caption_array = [
  '	<p>	<b>	Date:	</b>	6/8/2017	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Sajjad mp, Creative Commons Attribution-Share Alike 4.0 Internationa	</a>		</p>	',
  '	<p>	<b>	Date:	</b>	9/9/1995	<b>	Location:	</b>	Liverpool, England	<b>	Image Credit:	</b>	<a href="	https://www.mirrorpix.com/	" target="_blank">	Mirrorpix	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/19/1995	<b>	Location:	</b>	Liverpool, England	<b>	Image Credit:	</b>	<a href="	https://www.mirrorpix.com/	" target="_blank">	Mirrorpix	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/16/2002	<b>	Location:	</b>	Salt Lake City, Utah	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/people/56205607@N00	" target="_blank">	Dave O	</a>	 Creative Commons Attribution-Share Alike 2 Generic      	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://medium.com/@chijiokechiamaka26/internet-abuse-in-cyber-cafes-possible-solutions-db2269110bff	" target="_blank">	Unknown, possibly Chiamaka Chijioke	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/18/1995	<b>	Location:	</b>	Liverpool, England	<b>	Image Credit:	</b>	<a href="	https://www.mirrorpix.com/	" target="_blank">	Mirrorpix	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/2/1995	<b>	Location:	</b>	Liverpool, England	<b>	Image Credit:	</b>	<a href="	https://www.mirrorpix.com/	" target="_blank">	Mirrorpix	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2000	<b>	Location:	</b>	Leipzig, Germany	<b>	Image Credit:	</b>	<a href="	https://www.dpa.com/en	" target="_blank">	DPA	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/30/1999	<b>	Location:	</b>	Upper Hutt, New Zealand	<b>	Image Credit:	</b>	<a href="	https://uhcl.recollect.co.nz/	" target="_blank">	Upper Hutt City Library Heritage Collections, Upper Hutt Leader Collection	</a>	Creative Commons Attribution-NonCommercial 3 New Zealand Licence      	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Richmond, Virginia	<b>	Image Credit:	</b>	<a href="	https://the4cybercafe.net/	" target="_blank">	the4 Cybercafe	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Nairobi, Kenya	<b>	Image Credit:	</b>	<a href="	https://jiji.co.ke/nairobi-central/computer-and-it-services/cyber-cafe-office-supply-and-installation-services-5BRYthHYMz4XDevBs87edLox.html	" target="_blank">	Tonybills Systems	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Nairobi, Kenya	<b>	Image Credit:	</b>	<a href="	https://jiji.co.ke/nairobi-central/computer-and-it-services/cyber-cafe-office-supply-and-installation-services-5BRYthHYMz4XDevBs87edLox.html	" target="_blank">	Tonybills Systems	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/24/2005	<b>	Location:	</b>	Vancouver, Canada	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	10/24/2005	<b>	Location:	</b>	Vancouver, Canada	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	10/24/2005	<b>	Location:	</b>	Vancouver, Canada	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	10/24/2005	<b>	Location:	</b>	Vancouver, Canada	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	1/8/2008	<b>	Location:	</b>	Cyberia, London, England	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	8/1/1997	<b>	Location:	</b>	Utopia Cyber Cafe, Maidstone Great Britain	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	8/1/1997	<b>	Location:	</b>	Utopia Cyber Cafe, Maidstone Great Britain	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	4/7/2008	<b>	Location:	</b>	Ambleside, England	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	2/1/2007	<b>	Location:	</b>	Linda the Computer Lady\'s Internet Cafe, Cushing, Oklahoma (AKA Mind Trips)	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	2/1/2007	<b>	Location:	</b>	Linda the Computer Lady\'s Internet Cafe, Cushing, Oklahoma (AKA Mind Trips)	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	2/1/2007	<b>	Location:	</b>	Linda the Computer Lady\'s Internet Cafe, Cushing, Oklahoma (AKA Mind Trips)	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	2/1/2007	<b>	Location:	</b>	Linda the Computer Lady\'s Internet Cafe, Cushing, Oklahoma (AKA Mind Trips)	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	2/1/2007	<b>	Location:	</b>	Linda the Computer Lady\'s Internet Cafe, Cushing, Oklahoma (AKA Mind Trips)	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	2/1/2007	<b>	Location:	</b>	Linda the Computer Lady\'s Internet Cafe, Cushing, Oklahoma (AKA Mind Trips)	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	4/12/2020	<b>	Location:	</b>	Shibuya Tokyo Japan	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Bloomberg	" target="_blank">	Kentaro Takahashi, Bloomberg via Getty Images	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	possibly 5/3/2020	<b>	Location:	</b>	Tokyo, Japan	<b>	Image Credit:	</b>	<a href="	https://www.shutterstock.com/	" target="_blank">	Sutton Hibbert, Shutterstock	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/17/2000	<b>	Location:	</b>	Burger King, 86th Street, New York City	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/	" target="_blank">	Getty Images	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/30/2001	<b>	Location:	</b>	Bukhara, Uzbekistan	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=jeremy+sutton-hibbert&pseudoid=2C046F3B-FFEE-4C11-A0DB-016A4D4FD664&sortBy=relevant	" target="_blank">	jeremy sutton-hibbert / Alamy Stock Photo	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/25/2015	<b>	Location:	</b>	Likoma Island, Malawi	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Graham+Prentice&pseudoid=A814E049-9EBA-4F37-ADE4-E1B4D27E914B&sortBy=relevant	" target="_blank">	Graham Prentice	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=7AZWMY2WSJW9BML53HKK8UWY6X6VE8FXPHLUAQA3XK5LKQZRRF32GQT42M5JPQKN&name=ImageZoo&sortBy=relevant	" target="_blank">	ImageZoo	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2013	<b>	Location:	</b>	Beijing, China	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Lou-Foto&pseudoid=D0280695-966A-48E0-B406-CC01DEEE01F3&sortBy=relevant	" target="_blank">	Lou-Foto	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/24/2011	<b>	Location:	</b>	Beijing, China	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Lou-Foto&pseudoid=D0280695-966A-48E0-B406-CC01DEEE01F3&sortBy=relevant	" target="_blank">	Lou-Foto	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/27/2009	<b>	Location:	</b>	Nanchang, China	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Lou-Foto&pseudoid=D0280695-966A-48E0-B406-CC01DEEE01F3&sortBy=relevant	" target="_blank">	Lou-Foto	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Nicaragua	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=DYKDDRL6LYV9F85NQD48NN8KK9RJVHTQ3PFB3BPK3E34TWAE67ALQDSA4FV4J6YZ&name=Design+Pics+Inc&sortBy=relevant	" target="_blank">	Design Pics Inc	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/29/2015	<b>	Location:	</b>	Sao Domingos, Guinea Bissau	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=dianajarvisphotography.co.uk&pseudoid=DF5ACF74-A5E2-46E4-8D8A-5EB7B1061088&sortBy=relevant	" target="_blank">	Diana Jarvis Photography	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/24/2010	<b>	Location:	</b>	St. John\'s, Antigua und Barbuda	<b>	Image Credit:	</b>	<a href="	https://web.archive.org/web/20161015032216/http://www.panoramio.com/user/59988?with_photo_id=33800903	" target="_blank">	georama	</a>	Creative Commons Attribution 3 Unported        	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=Q7NHYUG6SPGM48K5E4X8487ZLV22KM3DRZVREK9667SHQEY5DE59J7PYXY4DGJDC&name=SuperStock&sortBy=relevant	" target="_blank">	SuperStock	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/17/2004	<b>	Location:	</b>	London, England	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	9/21/2004	<b>	Location:	</b>	Belgrade, Serbia	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=WR58P5F677XFLKN7GW34VE5JGRE4M5QY4HSQBCGPRCF75M25RANK3DR635T5GDN7&name=allOver+images&sortBy=relevant	" target="_blank">	allOver images	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/19/2014	<b>	Location:	</b>	Bielsko-Biala, Poland	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Gaj777	" target="_blank">	Kamil Czaiński	</a>	Creative Commons Attribution-Share Alike 4 International       	</p>	',
  '	<p>	<b>	Date:	</b>	1/27/2018	<b>	Location:	</b>	Bissau, Guinea-Bissau	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Peek+Creative+Collective&pseudoid=27E8088D-E6B3-40B0-AB37-603B7EEB75EE&sortBy=relevant	" target="_blank">	Peek Creative Collective	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 4/2021	<b>	Location:	</b>	State College, Pennsylvania (at penn state)	<b>	Image Credit:	</b>	<a href="	https://liveon.psu.edu/berks/dining/cyber-cafe	" target="_blank">	Penn State University	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/17/2000	<b>	Location:	</b>	Burger King, 86th Street, New York City	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/	" target="_blank">	Getty Images	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/20/2017	<b>	Location:	</b>	Buenos Aires, Argentina	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Jeffrey+Isaac+Greenberg+19+&pseudoid=3FD6BF16-C1E9-4124-AFCB-30EA3E08014A&sortBy=relevant	" target="_blank">	Jeffrey Isaac Greenberg 19+	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Ho Chi Minh City, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.sciencephoto.com/contributor/yfw/	" target="_blank">	Bjorn Svensson	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/15/2004	<b>	Location:	</b>	Barranquilla, Colombia	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Cafe_internet_uninorte.JPG	" target="_blank">	Centro de Producción Audiovisual, Oficina responsable del archivo fotográfico institucional, Universidad del Norte. Barranquilla Colombia.	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Beirut, Lebanon	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Alan+Gignoux&pseudoid=1BA9CDF0-8691-4A20-8D1E-055501F87992&sortBy=relevant	" target="_blank">	Alan Gignoux	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/24/2017	<b>	Location:	</b>	Curarrehue, Chile	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=KFQBA8PZNXLLXFYQNEYNQNABMH2GXLYDCAE88WLKQU74TXXHAASL34J2LNC9Y7SY&name=mauritius+images+GmbH&sortBy=relevant	" target="_blank">	mauritius images GmbH	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/7/2019	<b>	Location:	</b>	London, England	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=UrbanImages&pseudoid=67E1A3C3-06EE-4D80-89CD-8DA8E29CFAFC&sortBy=relevant	" target="_blank">	UrbanImages	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/7/2019	<b>	Location:	</b>	London, England	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=UrbanImages&pseudoid=67E1A3C3-06EE-4D80-89CD-8DA8E29CFAFC&sortBy=relevant	" target="_blank">	UrbanImages	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Aguascalientes, Mexico	<b>	Image Credit:	</b>	<a href="	https://www.dreamstime.com/jmrobledo_info	" target="_blank">	Juan Manuel Robledo	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/1/2016	<b>	Location:	</b>	Lexington, Virginia	<b>	Image Credit:	</b>	<a href="	https://www.apsva.us/design-and-construction/awards/copy-of-cyber-cafe/	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/28/2011	<b>	Location:	</b>	Chengdu, China 	<b>	Image Credit:	</b>	<a href="	https://www.dreamstime.com/pcruciatti_info	" target="_blank">	Piero Cruciatti	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 10/17/19	<b>	Location:	</b>	Bengaluru	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Unknown, possibly Batchu Rushali	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/19/2013	<b>	Location:	</b>	Mombasa, Kenya	<b>	Image Credit:	</b>	<a href="	https://en.wikipedia.org/wiki/User:Chaostar	" target="_blank">	Chaostar	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Kolkata, India	<b>	Image Credit:	</b>	<a href="	https://www.kolkataonline.in/city-guide/cyber-cafes-in-kolkata	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Cranberry Township, Pennsylvania	<b>	Image Credit:	</b>	<a href="	https://www.mbausa.org/services-and-benefits/conference-center/cyber-cafe/	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/19/2009	<b>	Location:	</b>	Kigali, Rwanda	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Moongateclimber	" target="_blank">	Moongateclimber	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Johnston Medical Mall, Smithfield, NC	<b>	Image Credit:	</b>	<a href="	https://www.johnstoncountync.org/listing/cyber-caf%C3%A9/1172/\	" target="_blank">	Johnston Country, North Carolina	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 10/11/2022	<b>	Location:	</b>	India	<b>	Image Credit:	</b>	<a href="	https://thepatriot.in/reports/the-era-of-neighbourhood-cyber-cafe-is-over-30690	" target="_blank">	Tanisha Seaxena	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Johnston Medical Mall, Smithfield, NC	<b>	Image Credit:	</b>	<a href="	https://www.johnstoncountync.org/listing/cyber-caf%C3%A9/1172/\	" target="_blank">	Johnston Country, North Carolina	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/20/2016	<b>	Location:	</b>	Meknes, Morocco	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Charles+O.+Cecil&pseudoid=E1254FDB-DF64-4FED-9DC1-D15177F5D462&sortBy=relevant	" target="_blank">	Charles O. Cecil	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	09/30/2008	<b>	Location:	</b>	Mostardas, Rio Grande do Sul, Brazil	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Travel+Pix&pseudoid=7EC3E239-2C6A-4762-B462-FED8944B26AF&sortBy=relevant	" target="_blank">	Travel Pix	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Delhi, India	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/16/2010	<b>	Location:	</b>	Nairobi, Kenya	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Steve+Turner&pseudoid=0471A283-9B5C-4BCB-836B-9A3010EE5ADE&sortBy=relevant	" target="_blank">	Steve Turner	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Bengaluru, India	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Tom+Bible&pseudoid=15DFCD23-1C2F-4B06-8A92-D955912183EB&sortBy=relevant	" target="_blank">	Tom Bible	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/26/1996	<b>	Location:	</b>	London, England	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Delhi, India	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 7/31/2016	<b>	Location:	</b>	New Delhi, India	<b>	Image Credit:	</b>	<a href="	https://www.hindustantimes.com/india-news/20-years-on-india-s-cyber-cafes-disappearing-as-pocket-internet-takes-over/story-vszaWMYND6Mm2lqOxkx5SK.html	" target="_blank">	Hindustan Times File Photo	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	London, England	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=British+Retail+Photography+&pseudoid=D61EFE1A-CB61-40A1-9E23-66334A4A226C&sortBy=relevant	" target="_blank">	British Retail Photography	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Obada-Oko, Nigeria	<b>	Image Credit:	</b>	<a href="	https://ng.infoaboutcompanies.com/Catalog/Ogun/Abeokuta/Sandwich-Shop/Roem-Internet-Cafe	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	India	<b>	Image Credit:	</b>	<a href="	https://sundayguardianlive.com/people-society/4334-does-nobody-visit-cyber-cafes-anymore	" target="_blank">	The Sunday Guardian	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/11/2007	<b>	Location:	</b>	Bishkek, Kyrgyzstan	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Vmenkov	" target="_blank">	Vmenkov	</a>	Creative Commons Attribution-Share Alike 3 Unported, 2.5 Generic, 2 Generic and 1 Generic	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Easter Island	<b>	Image Credit:	</b>	<a href="	https://www.dreamstime.com/astra490_info	" target="_blank">	Astra490	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2007	<b>	Location:	</b>	Waverly Station, Edinburgh, Scotland	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Public Domain	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	India	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Andrew+Woodley&pseudoid=9D518BBE-315C-41B6-9705-86ABB0F00EFE&sortBy=relevant	" target="_blank">	Andrew Woodley	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	7/19/2006	<b>	Location:	</b>	Paris, France	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Espace_milk.jpg	" target="_blank">	Janine Chedid	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	12/31/2007	<b>	Location:	</b>	holy city of Lalibela, Ethiopia	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=5NGDH8XKFF6FNTY3SK4EQYV7VQCMWZQW4GVJ8S33EM498Q4DUWU6SVLX829KG96S&name=Hemis&sortBy=relevant	" target="_blank">	Hemis	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/1/2020	<b>	Location:	</b>	Johor, Malaysia	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Chongkian,  Creative Commons Attribution-Share Alike 4.0 International	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 7/31/2016	<b>	Location:	</b>	Naveen Shahdara, New Delhi, India	<b>	Image Credit:	</b>	<a href="	https://www.hindustantimes.com/india-news/20-years-on-india-s-cyber-cafes-disappearing-as-pocket-internet-takes-over/story-vszaWMYND6Mm2lqOxkx5SK.html	" target="_blank">	Sonu Mehta/HT Photo	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/11/2004	<b>	Location:	</b>	Buenos Aires, Argentina	<b>	Image Credit:	</b>	<a href="	https://web.archive.org/web/20161011214117/http://www.panoramio.com/user/233756?with_photo_id=3425779	" target="_blank">	Ruben Pouquette	</a>	Creative Commons Attribution 3 Unported        	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=DYKDDRL6LYV9F85NQD48NN8KK9RJVHTQ3PFB3BPK3E34TWAE67ALQDSA4FV4J6YZ&name=Design+Pics+Inc&sortBy=relevant	" target="_blank">	Design Pics Inc Isabelle Schnoeckel	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/16/2010	<b>	Location:	</b>	Kedah Malaysia	<b>	Image Credit:	</b>	<a href="	https://en.wikipedia.org/wiki/File:Gazzointernetcafe.jpg	" target="_blank">	Chinesestar	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	7/25/1997	<b>	Location:	</b>	Moscow, Russia	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Andres%20Hernandez	" target="_blank">	Andres Hernandez/Liaison	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	7/25/1997	<b>	Location:	</b>	Moscow, Russia	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Andres%20Hernandez	" target="_blank">	Andres Hernandez/Liaison	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/28/2000	<b>	Location:	</b>	easyEverything Internet cafe, Times Square, New York	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Chris%20Hondros	" target="_blank">	Chris Hondros	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/28/2000	<b>	Location:	</b>	easyEverything Internet cafe, Times Square, New York	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Chris%20Hondros	" target="_blank">	Photo by Chris Hondros / Newsmakers	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/22/1995	<b>	Location:	</b>	New York City	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Jonathan%20Elderfield	" target="_blank">	Jonathan Elderfield / Liaison	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/22/1995	<b>	Location:	</b>	Cyber Cafe, New York	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Jonathan%20Elderfield	" target="_blank">	Jonathan Elderfield / Liaison	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/22/1995	<b>	Location:	</b>	Cyber Cafe, New York	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Jonathan%20Elderfield	" target="_blank">	Jonathan Elderfield / Liaison	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/22/1995	<b>	Location:	</b>	New York City	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Jonathan%20Elderfield	" target="_blank">	Jonathan Elderfield / Liaison	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/15/1997	<b>	Location:	</b>	San Francisco	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Eric%20Sander	" target="_blank">	Eric Sander / Liaison	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/15/1997	<b>	Location:	</b>	San Francisco	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Eric%20Sander	" target="_blank">	Eric Sander / Liaison	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	7/16/2003	<b>	Location:	</b>	Bangkok, Thailand	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Paula%20Bronstein	" target="_blank">	Paula Bronstein	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/23/2003	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=HOANG%20DINH%20NAM	" target="_blank">	HOANG DINH NAM / AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/2/2004	<b>	Location:	</b>	Mumbai, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=ROB%20ELLIOTT	" target="_blank">	ROB ELLIOTT	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/1/1996	<b>	Location:	</b>	Cyber Cafe, New York	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Suzanne%20Opton	" target="_blank">	Suzanne Opton	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/27/2002	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=HOANG%20DINH%20NAM	" target="_blank">	HOANG DINH NAM / AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/8/2001	<b>	Location:	</b>	Ranchi, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/detail/news-photo/indian-school-children-check-the-results-of-the-jharkhand-news-photo/51343107	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/27/2000	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=HOANG%20DINH%20NAM	" target="_blank">	HOANG DINH NAM / AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/16/2000	<b>	Location:	</b>	Calcutta, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=DESHAKALYAN%20CHOWDHURY	" target="_blank">	DESHAKALYAN CHOWDHURY	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/22/1998	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=HOANG%20DINH%20NAM	" target="_blank">	HOANG DINH NAM / AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/16/1999	<b>	Location:	</b>	Sao Paulo, Brazil	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=MARIE%20HIPPENMEYER	" target="_blank">	MARIE HIPPENMEYER	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	7/4/2006	<b>	Location:	</b>	Sherathang, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=DESHAKALYAN%20CHOWDHURY	" target="_blank">	DESHAKALYAN CHOWDHURY	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/22/2007	<b>	Location:	</b>	Mandalay, Myanmar	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Paula%20Bronstein]	" target="_blank">	Paula Bronstein	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/9/2008	<b>	Location:	</b>	Brasilia, Brazil	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=EVARISTO%20SA	" target="_blank">	EVARISTO SA	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/7/2008	<b>	Location:	</b>	Baghdad, Iraq	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Robert%20Nickelsberg	" target="_blank">	Robert Nickelsberg	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/9/2005	<b>	Location:	</b>	Mumbai, Maharashtra, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=The%20India%20Today%20Group	" target="_blank">	The India Today Group	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/9/2005	<b>	Location:	</b>	Mumbai, Maharashtra, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=The%20India%20Today%20Group	" target="_blank">	The India Today Group	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/9/2005	<b>	Location:	</b>	Mumbai, Maharashtra, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=The%20India%20Today%20Group	" target="_blank">	Soumik Kar / The India Today Group	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/5/2006	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=Bloomberg	" target="_blank">	Lucas Schifres / Bloomberg	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/20/1999	<b>	Location:	</b>	Tehran, Iran	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Kaveh%20Kazemi	" target="_blank">	Kaveh Kazemi	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/19/2009	<b>	Location:	</b>	Abidjan, Ivory Coast	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=AFP	" target="_blank">	AFP PHOTO/ SIA KAMBOU	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/11/2009	<b>	Location:	</b>	Abidjan, Ivory Coast	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=ISSOUF%20SANOGO	" target="_blank">	ISSOUF SANOGO	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/29/2001	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=HOANG%20DINH%20NAM	" target="_blank">	HOANG DINH NAM / AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/8/2007	<b>	Location:	</b>	Orchha, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Michael%20Greenwood	" target="_blank">	Michael Greenwood	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/11/1999	<b>	Location:	</b>	Sydney, Australia	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Alexis%20DUCLOS	" target="_blank">	Alexis DUCLOS	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/12/2000	<b>	Location:	</b>	Bangkok, Thailand	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Patrick%20AVENTURIER	" target="_blank">	Patrick AVENTURIER	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/12/2000	<b>	Location:	</b>	Bangkok, Thailand	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Patrick%20AVENTURIER	" target="_blank">	Patrick AVENTURIER	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/2/1998	<b>	Location:	</b>	Lulu\'s Restaurant, Washington DC	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=The%20Washington%20Post	" target="_blank">	James M. Thresher / The The Washington Post	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/28/1999	<b>	Location:	</b>	Nokialand, Helsinki, Finland	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Raphael%20GAILLARDE	" target="_blank">	Raphael GAILLARDE / Gamma-Rapho	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/1/1996	<b>	Location:	</b>	High Tech Coffee, Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Raphael%20GAILLARDE	" target="_blank">	Raphael GAILLARDE / Gamma-Rapho	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/1/1996	<b>	Location:	</b>	Orbital Coffee, Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Raphael%20GAILLARDE	" target="_blank">	Raphael GAILLARDE / Gamma-Rapho	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/1/1996	<b>	Location:	</b>	The "Shop", Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Raphael%20GAILLARDE	" target="_blank">	Raphael GAILLARDE / Gamma-Rapho	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/1/2000	<b>	Location:	</b>	Accra, Ghana	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Yann%20LATRONCHE	" target="_blank">	Yann LATRONCHE	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/1/2000	<b>	Location:	</b>	Accra, Ghana	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Yann%20LATRONCHE	" target="_blank">	Yann LATRONCHE	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/1/1995	<b>	Location:	</b>	The "Shop", Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Raphael%20GAILLARDE	" target="_blank">	Raphael GAILLARDE / Gamma-Rapho	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/29/1996	<b>	Location:	</b>	The "Shop", Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Raphael%20GAILLARDE	" target="_blank">	Raphael GAILLARDE / Gamma-Rapho	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/22/2007	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=HOANG%20DINH%20NAM	" target="_blank">	HOANG DINH NAM / AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/22/2007	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=HOANG%20DINH%20NAM	" target="_blank">	HOANG DINH NAM / AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/21/2006	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=HOANG%20DINH%20NAM	" target="_blank">	HOANG DINH NAM / AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/21/2006	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=HOANG%20DINH%20NAM	" target="_blank">	HOANG DINH NAM / AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/24/1996	<b>	Location:	</b>	The Web Cyber-Cafe, Besancon, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Francis%20DEMANGE	" target="_blank">	Francis DEMANGE / Gamma-Rapho	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/15/2000	<b>	Location:	</b>	Lorraine, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Francis%20DEMANGE	" target="_blank">	Francis DEMANGE / Gamma-Rapho	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/7/2000	<b>	Location:	</b>	Tehran, Iran	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Kaveh%20Kazemi	" target="_blank">	Kaveh Kazemi	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/21/2012	<b>	Location:	</b>	New Delhi, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Mail%20Today	" target="_blank">	Ramesh Sharma / The India Today Group	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/14/2004	<b>	Location:	</b>	Krakau, Poland	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Ulrich%20Baumgarten	" target="_blank">	Ulrich Baumgarten	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/15/2009	<b>	Location:	</b>	Beijing, China	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=LIU%20JIN	" target="_blank">	LIU JIN	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/1/2001	<b>	Location:	</b>	Patan, Nepal	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Peter%20Charlesworth	" target="_blank">	Peter Charlesworth	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/18/2013	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=Chau%20Doan	" target="_blank">	Chau Doan / LightRocket	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/18/2013	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=Chau%20Doan	" target="_blank">	Chau Doan / LightRocket	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Hmong, Sapa, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=Tuul%20%26%20Bruno%20Morandi	" target="_blank">	Tuul & Bruno Morandi	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/1/2004	<b>	Location:	</b>	Tunisian Desert	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Education%20Images	" target="_blank">	Education Images	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Steven%20Raymer	" target="_blank">	Steven Raymer	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Steven%20Raymer	" target="_blank">	Steven Raymer	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Bengaluru, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=David%20H.%20Wells	" target="_blank">	David H. Wells	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Ho Chi Minh City, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=Christophe%20Boisvieux	" target="_blank">	Christophe Boisvieux	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Bengaluru, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=David%20H.%20Wells	" target="_blank">	David H. Wells	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Ho Chi Minh City, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=Nik%20Wheeler	" target="_blank">	Nik Wheeler / Corbis	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Oruro, Bolivia	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=Anders%20Ryman	" target="_blank">	Anders Ryman	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/1/1995	<b>	Location:	</b>	Boston, Massachusettes 	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Brooks%20Kraft	" target="_blank">	Brooks Kraft	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Todd%20Gipstein	" target="_blank">	Todd Gipstein	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=Sebastien%20Desarmaux	" target="_blank">	Sebastien Desarmaux	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/31/2010	<b>	Location:	</b>	Taiyun, Shanxi, China	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Jie%20Zhao	" target="_blank">	Jie Zhao	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Beijing, China	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Liu%20Liqun	" target="_blank">	Liu Liqun	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/1/2001	<b>	Location:	</b>	Veerampattinam, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Fr%C3%A9d%C3%A9ric%20Soltan	" target="_blank">	Frédéric Soltan	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/1/2001	<b>	Location:	</b>	Veerampattinam, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Fr%C3%A9d%C3%A9ric%20Soltan	" target="_blank">	Frédéric Soltan	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/5/2014	<b>	Location:	</b>	Refugee camp in Za\'atari, Mafraq Governorate, Jordan	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Thierry%20Monasse	" target="_blank">	Thierry Monasse / Corbis	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	7/26/2014	<b>	Location:	</b>	Vientiane, Lao	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Thierry%20Monasse	" target="_blank">	Thierry Monasse	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/10/2003	<b>	Location:	</b>	Ouagadougou, Burkina Faso	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Gideon%20Mendel	" target="_blank">	Gideon Mendel	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/27/2017	<b>	Location:	</b>	Gaza City, Gaza	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Pacific%20Press	" target="_blank">	Geovien So / Pacific Press / LightRocket	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Web Bar, Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Web Bar, Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Web Bar, Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Web Bar, Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Web Bar, Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Web Bar, Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/25/1995	<b>	Location:	</b>	Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Bernard%20Annebicque%20	" target="_blank">	Bernard Annebicque / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	7/16/2007	<b>	Location:	</b>	Mumbai, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Hindustan%20Times	" target="_blank">	Kunal Patil / Hindustan Times	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/1/2000	<b>	Location:	</b>	Amsterdam	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=David%20Lefranc	" target="_blank">	David Lefranc	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/17/2010	<b>	Location:	</b>	Mumbai, India	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Hindustan%20Times	" target="_blank">	Kunal Patil / Hindustan Times	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/5/1995	<b>	Location:	</b>	Cyberia, London, England	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Mathieu%20Polak	" target="_blank">	Mathieu Polak / Sygma	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/14/1996	<b>	Location:	</b>	Tam Tam Cafe, Ho Chu Minh City, Vietnam. Ostensibly Vietnam\'s first cyber cafe	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/detail/news-photo/men-use-computers-at-tam-tam-cafe-which-bills-itself-as-news-photo/882702984	" target="_blank">	AFP	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/30/2018	<b>	Location:	</b>	Cairo, Egypt	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=KHALED%20DESOUKI	" target="_blank">	KHALED DESOUKI	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/20/2017	<b>	Location:	</b>	Buenos Aires, Argentina	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Jeff%20Greenberg	" target="_blank">	Jeff Greenberg	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/12/2021	<b>	Location:	</b>	Birmingham, England	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.co.uk/search/photographer?photographer=Mike%20Kemp	" target="_blank">	Mike Kemp	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/3/2019	<b>	Location:	</b>	Barcelona, Spain	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.com/search/photographer?photographer=Jeff%20Greenberg	" target="_blank">	Jeff Greenberg	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Geoff%20Brightling	" target="_blank">	Geoff Brightling	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Ron%20Chapple	" target="_blank">	Ron Chapple	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.gettyimages.no/search/photographer?photographer=Jules%20Frazier	" target="_blank">	Jules Frazier	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/8/11	<b>	Location:	</b>	Khumjung, Nepal	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Enrique+Lopez-Tapia&pseudoid=A98465E6-29C6-4BA4-8003-1BBB1005D746&sortBy=relevant	" target="_blank">	Enrique Lopez-Tapia, Nature Picture Library	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Bhilai, India	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/21/2009	<b>	Location:	</b>	Beijing, China	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Lou+Linwei&pseudoid=7C514144-ECC3-4481-9B93-94806C8570BF&sortBy=relevant	" target="_blank">	Lou Linwei	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/4/2016	<b>	Location:	</b>	Edinburgh, Scotland	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Alan+Wilson&pseudoid=80BF5FC9-E862-45C1-9F1C-5AAB9D78B556&sortBy=relevant	" target="_blank">	Alan Wilson	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/25/2011	<b>	Location:	</b>	Elgin, Illinois	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=B.+Leighty+/+Photri+Images&pseudoid=BC380866-A96C-41A3-944A-2360A8A29DE0&sortBy=relevant	" target="_blank">	B. Leighty / Photri Images	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/15/2000	<b>	Location:	</b>	Mali	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/people/39879513@N06	" target="_blank">	Toujours Passages	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	12/15/2000	<b>	Location:	</b>	Mali	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/people/39879513@N06	" target="_blank">	Toujours Passages	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Poitiers, France	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=David+Page&pseudoid=8EF4539B-B880-45D9-9164-C20CF376BAC5&sortBy=relevant	" target="_blank">	David Page	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Bangalore, India	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Tibor+Bognar&pseudoid=A4E0B046-6EED-409B-BE84-476C0978C017&sortBy=relevant	" target="_blank">	Tibor Bognar	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/7/2014	<b>	Location:	</b>	Jakarta, Java, Indonesia	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=6VTE9HHVWBW6LL8EC5S32KP5C8XUNHN7JRF8HR82JV8UM6U9QXVUHHVNUS7A99RY&name=Arterra+Picture+Library&sortBy=relevant	" target="_blank">	Marcia van der Meer / Arterra Picture Library	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/22/2014	<b>	Location:	</b>	Marrakesh, Morocco	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Anne+Marimuthu+Morocco&pseudoid=D9D1AC70-B472-4721-90A0-016E2E62D869&sortBy=relevant	" target="_blank">	Anne Marimuthu Morocco	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/31/2012	<b>	Location:	</b>	Chiquimula, Guatemala	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Instalaciones_de_Mega-Net.JPG	" target="_blank">	MegaNet Esquipulas	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	4/29/2010	<b>	Location:	</b>	Berat, Albania	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Maciej+Dakowicz&pseudoid=1BFA0942-F1F9-4F98-8D7B-9EE21AB6782A&sortBy=relevant	" target="_blank">	Maciej Dakowicz	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Luton Airport, Bedfordshire, England	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Greg+Balfour+Evans&pseudoid=F461022B-CCB5-4832-A15E-212757DBA14C&sortBy=relevant	" target="_blank">	Greg Balfour Evans	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/1/2005	<b>	Location:	</b>	Alice Springs, Australia	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:John_Hill	" target="_blank">	John Hill	</a>	Creative Commons Attribution-Share Alike 4 International       	</p>	',
  '	<p>	<b>	Date:	</b>	1/4/2013	<b>	Location:	</b>	Myanmar	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/people/89165847@N00	" target="_blank">	Michael Coghlan	</a>	Creative Commons Attribution-Share Alike 2 Generic       	</p>	',
  '	<p>	<b>	Date:	</b>	2000	<b>	Location:	</b>	Istanbul, Turkey	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Nevit	" target="_blank">	Nevit Dilmen	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	6/2/2011	<b>	Location:	</b>	Golden Princess cruise ship (travelling throughout Oceania)	<b>	Image Credit:	</b>	<a href="	https://en.wikipedia.org/wiki/User:Nv8200pa	" target="_blank">	Larry D. Moore	</a>	Licensed under CC BY-SA 3.0.        	</p>	',
  '	<p>	<b>	Date:	</b>	12/31/2006	<b>	Location:	</b>	Sana\'a, Yemen	<b>	Image Credit:	</b>	<a href="		" target="_blank">	(WT-shared) Shoestring at wts wikivoyage, public domain	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	7/3/2006	<b>	Location:	</b>	Rhoades, Greece	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Internet_cafe_sign.jpg	" target="_blank">	Daquella manera	</a>	Creative Commons CC0 1 Universal Public Domain Dedication. See also   	</p>	',
  '	<p>	<b>	Date:	</b>	8/19/2011	<b>	Location:	</b>	Berd City, Armenia	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Internet_club_in_Berd_city.jpg	" target="_blank">	Pandukht	</a>	Creative Commons CC0 1 Universal Public Domain Dedication     	</p>	',
  '	<p>	<b>	Date:	</b>	9/11/2012	<b>	Location:	</b>	Algarin, Mexico City, Mexico	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Internet_Cyberweb_1.0_Matriz_Sucursal_Algarin.jpg	" target="_blank">	Ivangonzalezn	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	7/24/2017	<b>	Location:	</b>	Cebu City, Phillipines	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:%C3%98yvind_Holmstad	" target="_blank">	Øyvind Holmstad	</a>	Creative Commons Attribution-Share Alike 4 International       	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 2006	<b>	Location:	</b>	Phillipines	<b>	Image Credit:	</b>	<a href="	https://www.techblade.ph/2019/02/the-disruption-in-internet-cafe-industry.html	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 7/14/2016	<b>	Location:	</b>	Neustadt, Germany	<b>	Image Credit:	</b>	<a href="	https://www-metropolnews-info.translate.goog/mp181799/neustadt-soziales-kaufhaus-fairness-startet-kostenloses-internetcafe?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp	" target="_blank">	Lebenswerk eG	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/1/2006	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://de.wikipedia.org/wiki/Benutzer:Ot	" target="_blank">	Ot	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	8/17/2013	<b>	Location:	</b>	Germany	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:NordhornerII	" target="_blank">	Nordhorner	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	6/4/2008	<b>	Location:	</b>	Munich, Germany	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Mattes	" target="_blank">	Mattes	</a>	Creative-Commons-Lizenz „Namensnennung – Weitergabe unter gleichen Bedingungen 3 nicht portiert   	</p>	',
  '	<p>	<b>	Date:	</b>	11/19/2008	<b>	Location:	</b>	Macao Dragon Company Ferry Shen Long	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:InternetCafe1.jpg	" target="_blank">	Ferryman1	</a>	and Macao Dragon          	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.dreamstime.com/karimala_info	" target="_blank">	Karin Hildebrand Lau	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.dreamstime.com/paha_l_info	" target="_blank">	Pavel Losevsky	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Dahab, Egypt	<b>	Image Credit:	</b>	<a href="	https://www.dreamstime.com/masr_info	" target="_blank">	Masr	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=WR58P5F677XFLKN7GW34VE5JGRE4M5QY4HSQBCGPRCF75M25RANK3DR635T5GDN7&name=allOver+images&sortBy=relevant	" target="_blank">	allOver images	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/1/2014	<b>	Location:	</b>	Dublin, Ireland	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Paul+Mayall+Ireland&pseudoid=0655C1FD-1F9C-4118-8D97-7428C4E80034&sortBy=relevant	" target="_blank">	Paul Mayall Ireland	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/20/2009	<b>	Location:	</b>	Bangkok, Thailand	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Peter+Treanor&pseudoid=7EF993C9-E0A5-46EE-A839-D389516B8B8D&sortBy=relevant	" target="_blank">	Peter Treanor	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	11/2/2010	<b>	Location:	</b>	11 Charing Cross Road, London, England, UK	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Alan+Gallery&pseudoid=3491E25B-8F6D-4031-ABD0-2BFF7BBDC207&sortBy=relevant	" target="_blank">	Alan Gallery	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/25/2008	<b>	Location:	</b>	Wellington, New Zealand	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=UrbanZone&pseudoid=82363AD3-E8CD-4856-A3C0-FBFBAD6A19EC&sortBy=relevant	" target="_blank">	UrbanZone	</a>	Alamy Stock Photo          	</p>	',
  '	<p>	<b>	Date:	</b>	7/11/2016	<b>	Location:	</b>	Grundarfjordur, Snaefellsnes Peninsula, Iceland	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=PearlBucknall&pseudoid=9338D335-76DB-481A-918F-89D8D104E85D&sortBy=relevant	" target="_blank">	PearlBucknall	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/28/2017	<b>	Location:	</b>	Portland, Maine	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Kevin+Galvin&pseudoid=C5D0AC6A-AE12-4AD7-B8E5-4629F3900396&sortBy=relevant	" target="_blank">	Kevin Galvin	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Mo\'orea Island, Tahiti	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=David+R.+Frazier+Photolibrary,+Inc.&pseudoid=D73D9102-8F24-4D85-867A-F6EF4C1B604C&sortBy=relevant	" target="_blank">	David R. Frazier Photolibrary, Inc.	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/30/2017	<b>	Location:	</b>	Morocco	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=MGC2REEDFNLQJ9JM7C6EA5EQS4S9MCCHZJQWMNFVW58U7BJJ4KQGD2LJBVJTG923&name=blickwinkel&sortBy=relevant	" target="_blank">	blickwinkel	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/26/2009	<b>	Location:	</b>	Pushkar, India	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Marcia+Chambers&pseudoid=6E0C6AC3-77CA-4494-8856-09A3946EC77A&sortBy=relevant	" target="_blank">	Marcia Chambers	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/20/2010	<b>	Location:	</b>	Christchurch, New Zealand	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Greg+Balfour+Evans&pseudoid=F461022B-CCB5-4832-A15E-212757DBA14C&sortBy=relevant	" target="_blank">	Greg Balfour Evans	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/27/2015	<b>	Location:	</b>	London, England	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Stephen+Parker&pseudoid=393A21CB-8C1F-4B70-9B82-2F4793BC8930&sortBy=relevant	" target="_blank">	Stephen Parker	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Nairobi, Kenya	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Peter+Treanor&pseudoid=7EF993C9-E0A5-46EE-A839-D389516B8B8D&sortBy=relevant	" target="_blank">	Peter Treanor	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Olaytaytambo Sacred Valley Peru	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=YDN65ZHYZD75VUQNWEQG9FXDNL2QADGP59KNZDNW7M7P3EYCSKQ3D39MCNG5ZEQD&name=David+Noton+Photography&sortBy=relevant	" target="_blank">	David Noton Photography	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/1/2010	<b>	Location:	</b>	Phu Quoc Island, Kien Giang, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=CKJJ5Y9KFBYR768R2S6R7NWUD56RZ5RHMZYMLGV8XHLPNHDVQ99CJFNHWBQGUUEK&name=PhotoAlto&sortBy=relevant	" target="_blank">	PhotoAlto	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/6/2010	<b>	Location:	</b>	La Digue, Seychelles	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=4UP2AYEJVDNNLNSA5NF2YCPYQDXTGQNU5ADSY79F3QG9A5EAA4YU2VE2DAMHDUCJ&name=travelstock44&sortBy=relevant	" target="_blank">	travelstock44	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/17/2017	<b>	Location:	</b>	Strasbourg, France	<b>	Image Credit:	</b>	<a href="	https://www.dreamstime.com/max5128_info	" target="_blank">	Max5128	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/5/2008	<b>	Location:	</b>	Rennell Island	<b>	Image Credit:	</b>	<a href="	https://en.wikipedia.org/wiki/User:Phenss	" target="_blank">	Phenss	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Jack+Sullivan&pseudoid=31A9058B-F702-4129-B043-A709C2A45DA0&sortBy=relevant	" target="_blank">	Jack Sullivan	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Mashhad, Iran	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Madeleine+Jettre&pseudoid=93B2605A-67CF-472B-98C2-1768B39E9F0D&sortBy=relevant	" target="_blank">	Madeleine Jettre	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/23/2011	<b>	Location:	</b>	Tafroute, Morocco	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Alistair+Laming&pseudoid=13530DFF-2591-4D69-88B7-F53A520E9384&sortBy=relevant	" target="_blank">	Alistair Laming	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 3/5/2021	<b>	Location:	</b>	Lima, Peru	<b>	Image Credit:	</b>	<a href="	https://www.limaeasy.com/peru-guide/stay-connected-peru/post-cellphones-wifi-internet-peru/internet-cafes	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Tortuguero, Costa Rica	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Martin+Bache&pseudoid=9F9253A7-0FD5-4A35-A359-21DEE60D0DF8&sortBy=relevant	" target="_blank">	Martin Bache	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/1/2007	<b>	Location:	</b>	Linda the Computer Lady\'s Internet Cafe, Cushing, Oklahoma (AKA Mind Trips)	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/wfryer/	" target="_blank">	Wesly Fryer	</a>	CC-BY-SA-2.1            	</p>	',
  '	<p>	<b>	Date:	</b>	9/1/2016	<b>	Location:	</b>	Wetzlar, Germany	<b>	Image Credit:	</b>	<a href="	https://www.dreamstime.com/colour59_info	" target="_blank">	Birgit Reitz Hofmann	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/29/2011	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=eye35&pseudoid=FB9206AC-B903-4A9A-9259-75F742C6545A&sortBy=relevant	" target="_blank">	eye35	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Yemen	<b>	Image Credit:	</b>	<a href="	https://www.dreamstime.com/pixelbird_info	" target="_blank">	Naci Yavuz	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/25/2020	<b>	Location:	</b>	"Facebook" Internet Cafe, Gondar, Ethiopia	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Sergi+Reboredo&pseudoid=EBF159EF-B2F7-43D1-8393-0EA3D194170F&sortBy=relevant	" target="_blank">	Sergi Reboredo	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/30/2011	<b>	Location:	</b>	Bukhara, Uzbekistan	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Gerner+Thomsen&pseudoid=4FE6660F-3E5B-4340-A655-DC3159AAA2A9&sortBy=relevant	" target="_blank">	Gerner Thomsen	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	7/2/2013	<b>	Location:	</b>	Sierra Leone	<b>	Image Credit:	</b>	<a href="	www.alamy.com/stock-photo/?name=jbdodane&pseudoid=37481651-1769-4C51-9FBB-3FC90C779570&sortBy=relevant	" target="_blank">	jbdodane https	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/7/2011	<b>	Location:	</b>	London, England	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Philip+Sayer&pseudoid=81EF0B0A-EDB7-4C9C-898F-37D851B65DB3&sortBy=relevant	" target="_blank">	Philip Sayer	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/24/2005	<b>	Location:	</b>	Laos	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:InternetShopLuangPhabang.jpg	" target="_blank">	Shoestring	</a>	public domain           	</p>	',
  '	<p>	<b>	Date:	</b>	4/17/2013	<b>	Location:	</b>	Israel	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:TZivyA	" target="_blank">	Zivya	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	11/11/2005	<b>	Location:	</b>	Seoul, South Korea	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/robfahey/	" target="_blank">	Hachimaki	</a>	 Creative Commons Attribution-Share Alike 2 Generic      	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 7/2020	<b>	Location:	</b>	New South Wales, Australia	<b>	Image Credit:	</b>	<a href="	https://www.tripadvisor.com/LocationPhotoDirectLink-g1899976-d19516137-i447190566-Legend_Internet_Cafe_Burwood-Burwood_Greater_Sydney_New_South_Wales.html	" target="_blank">	Unknown, possibly 思 黄	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 7/2020	<b>	Location:	</b>	New South Wales, Australia	<b>	Image Credit:	</b>	<a href="	https://www.tripadvisor.com/LocationPhotoDirectLink-g1899976-d19516137-i447190566-Legend_Internet_Cafe_Burwood-Burwood_Greater_Sydney_New_South_Wales.html	" target="_blank">	Unknown, possibly 思 黄	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 7/2020	<b>	Location:	</b>	New South Wales, Australia	<b>	Image Credit:	</b>	<a href="	https://www.tripadvisor.com/LocationPhotoDirectLink-g1899976-d19516137-i447190566-Legend_Internet_Cafe_Burwood-Burwood_Greater_Sydney_New_South_Wales.html	" target="_blank">	Unknown, possibly 思 黄	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/3/2007	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Level7cafe.jpg	" target="_blank">	HyprE	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	3/7/2006	<b>	Location:	</b>	Rosario, Argentina	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Pablo-flores	" target="_blank">	Pablo D. Flores	</a>	Creative Commons Attribution-Share Alike 2.5 Generic       	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Tulear, Madagascar	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=5NGDH8XKFF6FNTY3SK4EQYV7VQCMWZQW4GVJ8S33EM498Q4DUWU6SVLX829KG96S&name=Hemis&sortBy=relevant]	" target="_blank">	Hemis	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2006-2011	<b>	Location:	</b>	Barcelona, Spain	<b>	Image Credit:	</b>	<a href="	https://ca.wikipedia.org/wiki/Viquiprojecte:Fons_gr%C3%A0fic_Xavier_Badia	" target="_blank">	Xavier Badia Castellà	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	9/23/2011	<b>	Location:	</b>	Tafroute, Morocco	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Alistair+Laming&pseudoid=13530DFF-2591-4D69-88B7-F53A520E9384&sortBy=relevant	" target="_blank">	Alistair Laming	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Katraj, Pune, India	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/1/2022	<b>	Location:	</b>	WH Internet & Games, Mendoza, Argentina	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Jeffrey+Isaac+Greenberg+18+&pseudoid=61DE24CA-E2E2-426E-982F-8076E066BF26&sortBy=relevant	" target="_blank">	Jeffrey Isaac Greenberg 18+	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/29/2013	<b>	Location:	</b>	El Valle, Coclé, Panama	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Michael+Dwyer&pseudoid=B1FC33A1-DF4B-40BB-92C4-DF711C0F6BC8&sortBy=relevant	" target="_blank">	Michael Dwyer	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	6/2/2009	<b>	Location:	</b>	Augsburg, Bavaria, Germany	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=pbucknall&pseudoid=368D0133-1E22-4978-829F-3B5C47428283&sortBy=relevant	" target="_blank">	pbucknall	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2007	<b>	Location:	</b>	Luang Prabang, Laos	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Madeleine+Jettre&pseudoid=93B2605A-67CF-472B-98C2-1768B39E9F0D&sortBy=relevant	" target="_blank">	Madeleine Jettre	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/2/2017	<b>	Location:	</b>	Fes, Morocco	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=MJCQDE34LMNPAQ7K695N3R4WG5TTESJG5QHPR6UY77JVFTYX3E52PLQ2TTHEUA3W&name=agefotostock+&sortBy=relevant	" target="_blank">	agefotostock  J.D. Dallet	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Rhoades, Greece	<b>	Image Credit:	</b>	<a href="	https://www.tripadvisor.com.gr/LocationPhotoDirectLink-g635613-d2664480-i40759943-Internet_Cafe-Rhodes_Town_Rhodes_Dodecanese_South_Aegean.html	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	St Tropez, France	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Justin+Kase+ztwoz&pseudoid=6850F372-69FD-4C44-84F4-9D5E875A5C82&sortBy=relevant	" target="_blank">	Justin Kase ztwoz	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2005	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://en.wikipedia.org/wiki/User:Justinc	" target="_blank">	Justinc	</a>	 Creative Commons Genérica de Atribución/Compartir-Igual 2      	</p>	',
  '	<p>	<b>	Date:	</b>	7/30/2010	<b>	Location:	</b>	Las Vegas, Nevada	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Kumar+Sriskandan&pseudoid=7578BC2D-7185-4B19-94BB-ED4176B5BC16&sortBy=relevant	" target="_blank">	Kumar Sriskandan	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/26/2004	<b>	Location:	</b>	Jerusalem	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Cgmusselman	" target="_blank">	Cgmusselman	</a>	Public Domain           	</p>	',
  '	<p>	<b>	Date:	</b>	9/19/2018	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:NETLAND_INTERNET_CAFE.jpg	" target="_blank">	Sv2dft	</a>	Creative Commons Attribution-Share Alike 4 International       	</p>	',
  '	<p>	<b>	Date:	</b>	6/10/2008	<b>	Location:	</b>	Wien, Austria	<b>	Image Credit:	</b>	<a href="	https://web.archive.org/web/20161023144839/http://www.panoramio.com/user/4401384?with_photo_id=58763455	" target="_blank">	Ingo Neu	</a>	Creative Commons Attribution 3 Unported        	</p>	',
  '	<p>	<b>	Date:	</b>	2/15/2013	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:New_world,Pappireddipatti,newworld.jpg	" target="_blank">	Sivaram.selva	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	4/5/2011	<b>	Location:	</b>	London, England	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=RayArt+Graphics&pseudoid=78492D7E-F338-427F-ADBB-5121ECE91B19&sortBy=relevant	" target="_blank">	RayArt Graphics	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/1/2004	<b>	Location:	</b>	(Cyberia) London, England	<b>	Image Credit:	</b>	<a href="	https://12ft.io/proxy?q=https%3A%2F%2Fwww.telegraph.co.uk%2Fnews%2Fuknews%2F1470674%2FTen-years-of-Cyberia.html	" target="_blank">	Eddie Mulholland	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/19/2008	<b>	Location:	</b>	Nica Geeks Solar Powered Internet Cafe, San Juan Del Sur, Nacaragua	<b>	Image Credit:	</b>	<a href="	https://en.wikipedia.org/wiki/File:Nica_Geeks.jpg	" target="_blank">	Mat Honan	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	10/30/2009	<b>	Location:	</b>	Nungwi, Tanzania, Zanzibar	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Charles+O.+Cecil&pseudoid=E1254FDB-DF64-4FED-9DC1-D15177F5D462&sortBy=relevant	" target="_blank">	Charles O. Cecil	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/15/2011	<b>	Location:	</b>	Timbuktu Internate Cafe, Anne Arbor Michigan	<b>	Image Credit:	</b>	<a href="	https://www.yelp.com/biz_photos/timbuktu-internet-cafe-auburn-hills?select=jx_Qz0pvRiQnFjL1ULma1Q	" target="_blank">	Unknown, possibly the business owner	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/18/2011	<b>	Location:	</b>	Damascus, Syria	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Peter+Horree&pseudoid=85D45CE4-7183-44F5-B00A-AC25B003047F&sortBy=relevant	" target="_blank">	Peter Horree	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/18/2013	<b>	Location:	</b>	Cambridge, England	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Eduap	" target="_blank">	Eduap	</a>	 Creative Commons Attribution-Share Alike 3 Unported      	</p>	',
  '	<p>	<b>	Date:	</b>	6/1/1999	<b>	Location:	</b>	Netherlands	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Smiley.toerist	" target="_blank">	Smiley.toerist	</a>	Creative Commons Attribution-Share Alike 4 International       	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Rhoades, Greece	<b>	Image Credit:	</b>	<a href="	http://www.lindianet.gr/	" target="_blank">	Lindianet	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=L4L44PACEJG4SC4UAUY3CACN797YABNYZV652WGQ794BXDWNWUG7SLKRLZ94RLJL&name=PhotoAlto+sas&sortBy=relevant	" target="_blank">	Eric Audras PhotoAlto sas	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>		<b>	Location:	</b>	Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=David+R.+Frazier+Photolibrary,+Inc.&pseudoid=D73D9102-8F24-4D85-867A-F6EF4C1B604C&sortBy=relevant	" target="_blank">	David R. Frazier Photolibrary, Inc.	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Orbital Coffee, Paris, France	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=David+R.+Frazier+Photolibrary,+Inc.&pseudoid=D73D9102-8F24-4D85-867A-F6EF4C1B604C&sortBy=relevant	" target="_blank">	David R. Frazier Photolibrary, Inc.	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Rhoades, Greece	<b>	Image Credit:	</b>	<a href="	http://www.lindianet.gr/	" target="_blank">	Lindianet	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Rhoades, Greece	<b>	Image Credit:	</b>	<a href="	http://www.lindianet.gr/	" target="_blank">	Lindianet	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Rhoades, Greece	<b>	Image Credit:	</b>	<a href="	http://www.lindianet.gr/	" target="_blank">	Lindianet	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Rhoades, Greece	<b>	Image Credit:	</b>	<a href="	http://www.lindianet.gr/	" target="_blank">	Lindianet	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Ghana	<b>	Image Credit:	</b>	<a href="	https://www.ghanabusinessnews.com/2022/03/30/internet-cafe-business-slowing-down/	" target="_blank">	GNA	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Puerto Viejo Limon, Cosat Rica	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Realimage&pseudoid=0644F02E-9E60-4A25-979C-17C7F81D01EC&sortBy=relevant	" target="_blank">	Realimage	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/16/2011	<b>	Location:	</b>	Olkhon Island in Lake Baikal, Russia	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Retumejo_en_%C4%A4u%C4%B5iro_sur_Ol%C4%A5ono_(Rusujo)_003.jpg	" target="_blank">	Petr Adam Dohnálek	</a>	 Creative Commons Attribution-Share Alike 3 Czech Republic     	</p>	',
  '	<p>	<b>	Date:	</b>	10/2/2014	<b>	Location:	</b>	Sao Tome	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/people/21822583@N08	" target="_blank">	Chuck Moravec	</a>	 Creative Commons Attribution 2 Generic       	</p>	',
  '	<p>	<b>	Date:	</b>	6/19/2010	<b>	Location:	</b>	London England	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/loopzilla/	" target="_blank">	Gordon Joly	</a>	Attribution 2 Generic  (CC BY 2.0)      	</p>	',
  '	<p>	<b>	Date:	</b>	7/17/1997	<b>	Location:	</b>	Utopia Cyber Cafe, Maidstone Great Britain	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	7/17/1997	<b>	Location:	</b>	Utopia Cyber Cafe, Maidstone Great Britain	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	11/22/2001	<b>	Location:	</b>	Antaean cyber cafe, England	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	10/6/2007	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	8/20/2003	<b>	Location:	</b>	Bowness-on-Windermere, England	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	12/17/2007	<b>	Location:	</b>	Lothian, Scotland	<b>	Image Credit:	</b>	<a href="	https://www.flickr.com/photos/sarchi/	" target="_blank">	Sarchi	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Gwalior	<b>	Image Credit:	</b>	<a href="	https://www.justdial.com/Gwalior/Cyber-Cafes/nct-10151835	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Delhi, India	<b>	Image Credit:	</b>	<a href="	https://www.justdial.com/Delhi/Om-Cyber-Cafe-Near-Jagat-Farm-Knowledge-Park-Amritpuram-Market-Near-Ishan-Institute-Gamma-1-Greater-Noida/011PXX11-XX11-140825194803-X7I5_BZDET	" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/1/2013	<b>	Location:	</b>	San Francisco	<b>	Image Credit:	</b>	<a href="	https://www.tripadvisor.com/ShowUserReviews-g60713-d829278-r179852082-Quetzal_Internet_Cafe-San_Francisco_California.html#UR179852082	" target="_blank">	Flohsi	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	2/15/2011	<b>	Location:	</b>	Timbuktu Internate Cafe, Anne Arbor Michigan	<b>	Image Credit:	</b>	<a href="	https://www.yelp.com/biz_photos/timbuktu-internet-cafe-auburn-hills?select=jx_Qz0pvRiQnFjL1ULma1Q	" target="_blank">	Unknown, possibly the business owner	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	7/16/2009	<b>	Location:	</b>	Timbuktu Internate Cafe, Anne Arbor Michigan	<b>	Image Credit:	</b>	<a href="	https://www.yelp.com/biz_photos/timbuktu-internet-cafe-auburn-hills?select=jx_Qz0pvRiQnFjL1ULma1Q	" target="_blank">	Unknown, possibly the business owner	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	9/1999	<b>	Location:	</b>	Germsheim, Germany	<b>	Image Credit:	</b>	<a href="	https://www.fotocommunity.de/fotograf/hans-juergen-schmidtjever/842046	" target="_blank">	Hans Jürgen Schmidtjever	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Crete, Greece	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Eric+James&pseudoid=3E20B9A3-A816-4001-B3B6-285CBB9BBE98&sortBy=relevant	" target="_blank">	Eric James	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	4/11/2009	<b>	Location:	</b>	Salvador, Bahia, Brazil	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=ULW7G5BKQCMP3XBBLSDZT8CQB992KAM5UDQUFUBZTMK4Y3NW3GB8KZM3QJWLBZ5V&name=imageBROKER&sortBy=relevant	" target="_blank">	imageBROKER	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	1/3/2003	<b>	Location:	</b>	Kita, Mali	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Sirandou.net_cybercafe_IICD_Kita,_Mali.jpg	" target="_blank">	IICD	</a>	Creative Commons Attribution 2 Generic        	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Hanoi, Vietnam	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Peter+Treanor&pseudoid=7EF993C9-E0A5-46EE-A839-D389516B8B8D&sortBy=relevant	" target="_blank">	Peter Treanor	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	8/14/2016	<b>	Location:	</b>	Landstraße, Vienna	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/User:Herzi_Pinki	" target="_blank">	Herzi Pinki	</a>	Creative Commons Attribution-Share Alike 4 International       	</p>	',
  '	<p>	<b>	Date:	</b>	8/31/2010	<b>	Location:	</b>	Chame , Manang , Gandaki Zone , Nepal	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=APURPPMWJHLUD8DHEZCMXW5PGBMBU3WDNAN5FD4DENAF6RRDBRGT27TX9QGS284T&name=Dinodia+Photos&sortBy=relevant	" target="_blank">	Dinodia Photos	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	12/2/2010	<b>	Location:	</b>	Varanasi, India	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Maciej+Dakowicz&pseudoid=1BFA0942-F1F9-4F98-8D7B-9EE21AB6782A&sortBy=relevant	" target="_blank">	Maciej Dakowicz	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	3/25/2003	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?cid=PFHPBHQTC4S2XQMFJN3ZJ3Y6MC9BSGPDT2EH8UJHGYJCDQ9XBWYCFUEVVPW2Z6W5&name=Picade+LLC&sortBy=relevant	" target="_blank">	Nick Servian Picade LLC	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Vietnam	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Ahmedabad, India	<b>	Image Credit:	</b>	<a href="		" target="_blank">	Unknown	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	5/6/2014	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Wangba_2.JPG	" target="_blank">	Zcm11	</a>	Creative Commons Attribution-Share Alike 3 Unported       	</p>	',
  '	<p>	<b>	Date:	</b>	10/19/2012	<b>	Location:	</b>	Riau, Indonesia	<b>	Image Credit:	</b>	<a href="	https://web.archive.org/web/20161024170616/http://www.panoramio.com/user/7223604?with_photo_id=80818225	" target="_blank">	amris ling	</a>	Creative Commons Attribution 3 Unported        	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Iocoturio, Argentina	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=David+R.+Frazier+Photolibrary,+Inc.&pseudoid=D73D9102-8F24-4D85-867A-F6EF4C1B604C&sortBy=relevant	" target="_blank">	David R. Frazier Photolibrary, Inc.	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	10/27/2020	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://commons.wikimedia.org/wiki/File:Zona_PC.jpg	" target="_blank">	Bruno Rafael Tavares Pereira	</a>	This file is licensed under the Creative Commons Attribution-Share Alike 4 International 	</p>	',
  '	<p>	<b>	Date:	</b>	Possibly 7/21/ 2001	<b>	Location:	</b>	Unknown	<b>	Image Credit:	</b>	<a href="	https://12ft.io/proxy?q=https%3A%2F%2Fwww.telegraph.co.uk%2Ffoodanddrink%2F3290457%2FCybercafes-the-crossroads.html	" target="_blank">	Martin Pope	</a>	            	</p>	',
  '	<p>	<b>	Date:	</b>	Unknown	<b>	Location:	</b>	Honduras	<b>	Image Credit:	</b>	<a href="	https://www.alamy.com/stock-photo/?name=Charles+O.+Cecil&pseudoid=E1254FDB-DF64-4FED-9DC1-D15177F5D462&sortBy=relevant	" target="_blank">	Charles O. Cecil	</a>	            	</p>	'
]

let current_index = 0;

function image_starter(){
  current_index = 0;
  document.getElementById('image_displayer').src = `./images/${image_array[current_index]}`;
  document.getElementById('captiontext').innerHTML = caption_array[current_index];
  console.log("current caption",caption_array[current_index]);
}

function get_random_image(){
  current_index = Math.floor(Math.random() * image_array.length);
  console.log("Current Index", current_index);
  document.getElementById('image_displayer').src = `./images/${image_array[current_index]}`;
  document.getElementById('captiontext').innerHTML = caption_array[current_index];
  console.log("current caption",caption_array[current_index]);
}

function get_next_image(){
  current_index = (current_index + 1); 
  if (current_index > image_array.length -1){
    current_index = 0;
  }
  console.log("Current Index", current_index);
  document.getElementById('image_displayer').src = `./images/${image_array[current_index]}`;
  document.getElementById('captiontext').innerHTML = caption_array[current_index];
  console.log("current caption",caption_array[current_index]);
}

function get_prev_image(){
  current_index = (current_index - 1);
  if (current_index < 0){
    current_index = image_array.length-1;
  }
  console.log("Current Index", current_index);
  document.getElementById('image_displayer').src = `./images/${image_array[current_index]}`;
  document.getElementById('captiontext').innerHTML = caption_array[current_index];
  console.log("current caption",caption_array[current_index]);
}
